retab

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -180,68 +180,68 @@ fi
 # functions {{{ 
 
 extract () {
-	local remove_archive
-	local success
-	local file_name
-	local extract_dir
-	if (( $# == 0 ))
-	then
-		echo "Usage: extract [-option] [file ...]"
-		echo
-		echo Options:
-		echo "    -r, --remove    Remove archive."
-		echo
-		echo "Report bugs to <sorin.ionescu@gmail.com>."
-	fi
-	remove_archive=1 
-	if [[ "$1" = "-r" ]] || [[ "$1" = "--remove" ]]
-	then
-		remove_archive=0 
-		shift
-	fi
-	while (( $# > 0 ))
-	do
-		if [[ ! -f "$1" ]]
-		then
-			echo "extract: '$1' is not a valid file" >&2
-			shift
-			continue
-		fi
-		success=0 
-		file_name="$( basename "$1" )" 
-		extract_dir="$( echo "$file_name" | sed "s/\.${1##*.}//g" )" 
-		case "$1" in
-			(*.tar.gz|*.tgz) tar xvzf "$1" ;;
-			(*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
-			(*.tar.xz|*.txz) tar --xz --help &> /dev/null && tar --xz -xvf "$1" || xzcat "$1" | tar xvf - ;;
-			(*.tar.zma|*.tlz) tar --lzma --help &> /dev/null && tar --lzma -xvf "$1" || lzcat "$1" | tar xvf - ;;
-			(*.tar) tar xvf "$1" ;;
-			(*.gz) gunzip "$1" ;;
-			(*.bz2) bunzip2 "$1" ;;
-			(*.xz) unxz "$1" ;;
-			(*.lzma) unlzma "$1" ;;
-			(*.Z) uncompress "$1" ;;
-			(*.zip|*.war|*.jar) unzip "$1" -d $extract_dir ;;
-			(*.rar) unrar x -ad "$1" ;;
-			(*.7z) 7za x "$1" ;;
-			(*.deb) mkdir -p "$extract_dir/control"
-				mkdir -p "$extract_dir/data"
-				cd "$extract_dir"
-				ar vx "../${1}" > /dev/null
-				cd control
-				tar xzvf ../control.tar.gz
-				cd ../data
-				tar xzvf ../data.tar.gz
-				cd ..
-				rm *.tar.gz debian-binary
-				cd .. ;;
-			(*) echo "extract: '$1' cannot be extracted" >&2
-				success=1  ;;
-		esac
-		(( success = $success > 0 ? $success : $? ))
-		(( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
-		shift
-	done
+    local remove_archive
+    local success
+    local file_name
+    local extract_dir
+    if (( $# == 0 ))
+    then
+        echo "Usage: extract [-option] [file ...]"
+        echo
+        echo Options:
+        echo "    -r, --remove    Remove archive."
+        echo
+        echo "Report bugs to <sorin.ionescu@gmail.com>."
+    fi
+    remove_archive=1 
+    if [[ "$1" = "-r" ]] || [[ "$1" = "--remove" ]]
+    then
+        remove_archive=0 
+        shift
+    fi
+    while (( $# > 0 ))
+    do
+        if [[ ! -f "$1" ]]
+        then
+            echo "extract: '$1' is not a valid file" >&2
+            shift
+            continue
+        fi
+        success=0 
+        file_name="$( basename "$1" )" 
+        extract_dir="$( echo "$file_name" | sed "s/\.${1##*.}//g" )" 
+        case "$1" in
+            (*.tar.gz|*.tgz) tar xvzf "$1" ;;
+            (*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
+            (*.tar.xz|*.txz) tar --xz --help &> /dev/null && tar --xz -xvf "$1" || xzcat "$1" | tar xvf - ;;
+            (*.tar.zma|*.tlz) tar --lzma --help &> /dev/null && tar --lzma -xvf "$1" || lzcat "$1" | tar xvf - ;;
+            (*.tar) tar xvf "$1" ;;
+            (*.gz) gunzip "$1" ;;
+            (*.bz2) bunzip2 "$1" ;;
+            (*.xz) unxz "$1" ;;
+            (*.lzma) unlzma "$1" ;;
+            (*.Z) uncompress "$1" ;;
+            (*.zip|*.war|*.jar) unzip "$1" -d $extract_dir ;;
+            (*.rar) unrar x -ad "$1" ;;
+            (*.7z) 7za x "$1" ;;
+            (*.deb) mkdir -p "$extract_dir/control"
+                mkdir -p "$extract_dir/data"
+                cd "$extract_dir"
+                ar vx "../${1}" > /dev/null
+                cd control
+                tar xzvf ../control.tar.gz
+                cd ../data
+                tar xzvf ../data.tar.gz
+                cd ..
+                rm *.tar.gz debian-binary
+                cd .. ;;
+            (*) echo "extract: '$1' cannot be extracted" >&2
+                success=1  ;;
+        esac
+        (( success = $success > 0 ? $success : $? ))
+        (( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
+        shift
+    done
 }
 
 function twitchl(){
@@ -283,11 +283,11 @@ export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
 
 # fe [FUZZY PATTERN] - Open the selected file with the default editor
 fe() {
-	IFS='
-	'
-	local declare files=($(fzf-tmux --query="$1" --select-1 --exit-0))
-	[[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
-	unset IFS
+    IFS='
+    '
+    local declare files=($(fzf-tmux --query="$1" --select-1 --exit-0))
+    [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
+    unset IFS
 }
 
 # fd - cd to selected directory
@@ -300,8 +300,8 @@ fd() {
 
 # fda - including hidden directories
 fda() {
-	local dir
-	dir=$(find ${1:-.} -type d 2> /dev/null | fzf +m) && cd "$dir"
+    local dir
+    dir=$(find ${1:-.} -type d 2> /dev/null | fzf +m) && cd "$dir"
 }
 
 v() {
@@ -333,8 +333,8 @@ kd() {
 
 # fda - including hidden directories
 kda() {
-	local dir
-	dir=$(find ${1:-.} -type d 2> /dev/null | sk -m) && cd "$dir"
+    local dir
+    dir=$(find ${1:-.} -type d 2> /dev/null | sk -m) && cd "$dir"
 }
 
 #}}}
